### ISSUE TITLE
Currency Delivery in our world

### ISSUE THREAD

**Issue by Streexfoxtrot** [HalcyonGrid/halcyon#116]
I am working on our Halcyon grid and I'm assisting our owners. When users purchase currency it's taking a HUGE chunk out of what is being delivered. We have it set to 500(grid) = $1 but when you get a delivery it's taking a percentage of the currency away. 

We have set it many different ways but we're not seeming to set it right. 
Even under Economy management if we set the exchange to 0 it's still not delivering the full amounts, is there someone who could help me understand what we need to do to ensure that if a customer Buys 1000($) in grid currency that they receive it? 

Please note I'm not a programmer but I would like to figure out a fix to pass along to the person who is working our grid set up.

**Comment by kf6kjg** [comment]
I think this is more of an issue with the webserves, possibly the MyWorld software if you are using that, than Halcyon itself.  Maybe Vinhold can confirm?

**Comment by Vinhold** [comment]
This is not a Halcyon problem. The real source of trouble is in the website with the Buy$ page process which is using PayPal. PayPal's formula for precalculating their fee has changed for non-USA currencies, with different rates for a long list of countries. This has made it impossible to maintain as it will require each account to post their country of origin or be able to accurately detect that from the browser connection. I have disabled the inworld currency option for now in the MyWorld website.

**Comment by kf6kjg** [comment]
Closing as not an issue with Halcyon. If you think this closure is a mistake please let me know and we can discuss where the error is.

**Comment by Yichard** [comment]
This has been discussed in Mundos Market meetings, and indeed is an issue with Paypal, which cannot currently be solved.
I asked how it works to the Stripe support. They seem to have more predictable fees, only 2-3 categories. But the first to try will find out how it really works, lol
