### ISSUE TITLE
Remove saveexplicit oar Command

### ISSUE THREAD

**Issue by Vinhold** [HalcyonGrid/halcyon#13]
This is a carry over issue from https://github.com/InWorldz/halcyon/issues/344.

saveexplicit oar < region name > < oar filename > < store_assets > - Save a region's data to an OAR archive

This command does nothing and apparently was only a stub for a variant option of the save oar command. Since it serves no useful purpose, it should be removed from the command list, any unique process it may have served could be added to the save oar command. Specifically since the simulator is restricted to only one region instance, identifying a <region_name> from several that may be running is not possible, only the one active region can apply.

**Comment by ddaeschler** [comment]
saveexplicit was used to guarantee when a save command was sent or typed that it was sent to the correct simulator. It was because the automated system somtimes sent the command to the wrong instance if it was misconfigured causing regions to be overwritten with other regions contents.

There are reasons for everything. All you have to do is ask.

**Comment by Vinhold** [comment]
That sounds a lot like an implementation problem that did not have a context for what region was being processed. In current Halcyon operation, each region instance has a unique "address" by combined server and port number assigned to it, to be processed by its command process. Even if it is running as a service process and not a command window, that would still remain true. So is that command structure still relevant to how the simulators are working now? What process was sending that command that would not know what region simulator was to process it?

**Comment by kf6kjg** [comment]
From the above discussion it looks like this command is working as intended.  If it needs to gain some documentation or console output, that's good reason for another issue.
