### ISSUE TITLE
Is this "Halcyon"?

### ISSUE THREAD

**Issue by mdickson** [HalcyonGrid/halcyon#15]
If the premise is to do new releases of "Halcyon" from this repository I'd like to clarify that the license prohibits doing that without prior written permission of the contributors.  You certainly have the right to do source or binary releases but the name itself can't be used without permission.  Now you may not intend to release it that way and if so there's no problem.  I have a fork as well to preserve the state of the tree and so I can use some of the code in my own projects.  But as above if I do I won't be calling it Halcyon on release.

So you can do a new software distribution, you just can't call it Halcyon if you do.

**Comment by EleniaLL** [comment]
HalcyonGrid has already been given express permission by the copyright holder of InWorldz.

**Comment by kf6kjg** [comment]
Thank you Elenia.  So to answer the question, yes this is officially Halcyon.

**Comment by mdickson** [comment]
Just to be clear I never assigned copyright to my work to InWorldz.  I still own the IP I created under the same license terms as Halcyon.  Use it if you want but it remains my IP.  I'll show the same respect to the contributions others made when/if I port them to OpenSim.

**Comment by kf6kjg** [comment]
Of course.  The issue here was simply the name "Halcyon" not the code IP.
