### ISSUE TITLE
SSL Exception during User.Grid load, on connection to MySQL?

### ISSUE THREAD

**Issue by appurist** [HalcyonGrid/halcyon#151]
This may be a problem with recent Windows updates, it's the first time I've tried to start up a region in a couple of years, and Googling the issue implies that it may be related to systems dropping support for earlier TLS versions in HTTPS connections.

This doesn't make a lot of sense to me since we use MySQL.Data.dll and in my case a HTTP localhost connection, but I'll add this in case anyone has seen this. I struggled with it for about an hour last night, with no luck.

Note that MySQL Workbench has no trouble connecting. I have tried using `localhost` and `127.0.0.1` in the connection string to no effect.

I suspect there may be a new option we need to call that WB is using to tell it to make an insecure local connection, or may I need to install an SSL cert now for localhost testing.

Is anyone else having trouble connecting in a localhost setup?

```
>OpenSim.Grid.UserServer.exe
02:20:44 - [STARTUP]: Beginning startup processing
02:20:44 - [PLUGINS]: Initializing addin manager
02:20:44 - [PLUGINS]: Cleaning out addins directory
02:20:45 - [PLUGINS]: Loading extension point /OpenSim/InventoryStorage
02:20:45 - [PLUGINS]: Trying plugin /OpenSim/InventoryStorage/InventoryMySQL
02:20:45 - [PLUGINS]: Plugin Loaded: Halcyon.Data.Inventory.MySQL
02:20:45 - [STARTUP]: Establishing data connection
02:20:45 - [PLUGINS]: Loading extension point /OpenSim/UserData
02:20:45 - [PLUGINS]: Trying plugin /OpenSim/UserData/MySQLUserData
02:20:45 - [PLUGINS]: Plugin Loaded: OpenSim.Data.MySQL

Unhandled Exception: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The Local Security Authority cannot be contacted
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at MySql.Data.MySqlClient.NativeDriver.StartSSL()
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool..ctor(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPoolManager.GetPool(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at OpenSim.Data.SimpleDB.MySQLSimpleDB.OpenConnection() in C:\DevSL\InWorldz\halcyon\OpenSim\Data\SimpleDB\MySQLSimpleDB.cs:line 88
 
```

**Comment by appurist** [comment]
[Mostly resolved]

I saw a reference to the problem having gone away by upgrading to "the latest" MySQL. So I figured the reverse may be true as well. I was running 5.7 and decided to try downgrading to an older installer I still had (5.5.27) and the latest compatible Workbench (6.3.10). This worked! The grid services have no trouble connecting to MySQL now.

So I think what this means is there is some work to perform, at least investigation, if we are to support newer MySQL versions, although that is probably expected. Also I noticed some certificate files in the MySQL 5.7 folder so it may be necessary to install them or a CA in order to have access in 5.7 and later.

I'm going to close this but get Ricky's attention so that he's aware too. @kf6kjg

**Comment by kf6kjg** [comment]
Thanks for the update on what happened and how you worked around it.

**Comment by mdickson** [comment]
The Oracle MySQL driver is fairly finicky wrt SSL/TLS versions and Ubuntu around 22.04 dropped support for a bunch of older SSL configurations.  I solved this by moving to the Pomello connector which does the right thing and actually supports SSL effectively as well as with more modern authentication schemes.  It also gives about a 20% performance boost over the Oracle connector

**Comment by appurist** [comment]
Thanks Mike. Generally I use PostgreSQL these days, but I'm trying to fire up a local Halcyon server environment after a few years of not having one and so I'm finding places where things are a bit out of date now.

That's a great tip about the Pomello connector. 

FYI, I'm actually just using XAMPP for my local machine, in order to get a quick Apache, PHP and SQL server for Halcyon and web testing and experiments. Which means connecting Halcyon to MariaDB; I _might_ be the first to try that although I can't imagine others haven't. The only issue I've seen is MySQL Workbench (6.3) isn't really compatible with MariaDB so I've switched to the [HeidiSQL](https://www.heidisql.com/) UI for MariaDB. All is good there so far.

**Comment by mdickson** [comment]
If you're using something besides the oracle MySQL definitely look at Pomello. It supports  more of the derivitive versions of MySQL.  I used Percona for a while and had a similar issue.
________________________________

**Comment by sonjamichelle** [comment]
I've used MariaDB once or twice with Halcyon. From what I can recall it worked fairly well. Though you are right abuout MariaDB and Workbench. They don't really play well together.

MySQL 5.7 or lower tend to work the best with Halcyon (and with OpenSim 0.9.2 and lower) If using MySQL 8 you DO have to pay attention to the authentication method you choose during SQL setup.
