### ISSUE TITLE
not compile nothing with runprebuild.sh

### ISSUE THREAD

**Issue by BogusCurry** [HalcyonGrid/halcyon#20]
Hello ;D
I have clone the code unter Linux Mint 19 and then I would run runprebuild.sh, but if comes nothing. I have no Idea, what I have make wrong. I have install Mono 5.10.1.20. 
What I make wrong ?

Bye
Bogus | GridTalk.de

**Comment by appurist** [comment]
The `runprebuild.sh` script just copies some required files. If you want to build Halcyon too, that is a separate step: run `msbuild` too.

Or run both together with `runprebuild.sh && msbuild`.

**Comment by kf6kjg** [comment]
This is working as documented at https://github.com/HalcyonGrid/halcyon/wiki/Development

The CLI-only build process is used in https://github.com/HalcyonGrid/halcyon/blob/master/.appveyor.yml#L55 and the full commandline build would be:
`runprebuild.sh && msbuild /p:DefineConstants="_MONO_CLI_FLAG_" Halcyon.sln`

If that solves the problem, please close this issue. Thank you.

**Comment by BogusCurry** [comment]
ok thanks for your answers ;D

**Comment by BogusCurry** [comment]
So I have now compile the code, but this error messages comes in console .. 
https://paste.md-5.net/dawuyukalo.coffee

**Comment by kf6kjg** [comment]
Ah, that meant you didn't do the nuget restore before you tried to build.
From CLI that's `nuget restore Halcyon.sln` as you can see in the `before_build` stage of the `appveyor.yml` file linked to before.  Do this, then run the command I sent you before again.

All these steps are automatic in the GUI tools.
