### ISSUE TITLE
Add halMessageObject() function, equivalent to osMessageObject()

### ISSUE THREAD

**Issue by zauberparacelsus** [HalcyonGrid/halcyon#68]
I'd like to propose the addition of halMessageObject(), equivalent to opensim's osMessageObject().  This has been discussed and was rejected due to problems with osMessageObject(), but I would like to propose its addition into Halcyon anyways in order to make it easier to bring opensim scripts into Halcyon.

**Comment by kf6kjg** [comment]
1. What were the issues previously raised?
2. What function signature would you propose? osMessageObject's signature looks to be missing a useful return value IMHO.
3. How would you suggest to implement reception of the message?
4. How would you suggest to implement error handling, such as the destination not existing, throttling limits being hit, or a fundamental service not being active?  Should the sending script even know of the error?
5. What abuse cases can be predicted and how would you suggest to handle them?

Also, what benefit does it introduce over using the HTTP commands, llRegionSayTo?  In the HTTP vs this command case I see both needing a known central registry that the sender can query for getting the URL/UUID of the destination, so there's no benefit there.

I'm not trying to shut down the question, but asking for a good thought at how it'd be best implemented to add good and useful functionality to Halcyon.

**Comment by emperorstarfinder** [comment]
These are the same questions I would ask as well.

Cursory review of the logic in OpenSim does seem that there would be a missing value or two (but then I would expect that in XEngine and likely YEngine in OpenSim). 

 As far as what benefit this has would be that it could potentially allow objects to communicate grid-wide even if they are not in the same region.  Might be good for networked vendors as an example.  

Though I don't think I would necessarily rely on any OSSL functions being very secure.  But I will be interested as well to what the answers to these questions Rick asks are.

**Comment by zauberparacelsus** [comment]
osMessageObject was not really well thought out or designed.  And most of the questions/concerns you listed just highlight the problems.

The main issue is that the message is received via the dataserver event, meaning that any script with a dataserver event can be messaged.  Because the dataserver event is used for other things like notecard-reading, any object with a dataserver event could be attacked merely by obtaining its UUID.  Now, dataserver functions like llGetNotecardLine do return a key that can be stored and compared with the key given by the dataserver event in order to filter out messages, but not every scripter is going to do that.  And even if the dataserver event is coded to filter the recieved messages (by UUID or other means), that won't prevent osMessageObject from being used to DDoS an object, especially since osMessageObject has no delay.

If I were to make any changes/improvements to it that would not totally break compatibility with opensim, I would restrict it so that you can only message your own objects, and make the region throttle the rate at which messages can be sent to a particular object.  That greatly reduces the security concerns and DDoS potential, but not totally (the owner restriction still leaves it vulnerable to "gift attacks")

**Comment by zauberparacelsus** [comment]
Oh, and to answer Ricky's other question, the *only* benefit it has over HTTP commands is that it is simpler and easier to use.  But as is often the case, simplification can mean hiding or ignoring the complexity.

**Comment by mdickson** [comment]
osMessageObject is essentially the same as llRegionSayTo() with the difference being no channel is used and the value is delivered via a data server event (so a channel isn't needed).    The big issue with it is that it can indeed be used to DDoS a script.  I honestly can't think of a case where I'd use it over llRegionSayTo().  

Not sure whats "missing" wrt to values or why its poorly designed (other than the DDoS issue mentioned). Its pretty straightforward in its function. I just don't think its needed.

**Comment by zauberparacelsus** [comment]
The "poorly designed" aspect is that it goes through the dataserver event.  Normally, the dataserver event only fires in response to script functions that were either called from within the same script or within the same prim.

osMessageObject changes that assumption, creating a security issue where none had previously existed.  And yes, any time you call the dataserver event, you should always check against the key returned when the event is called.  However, not all scripters do that, either out of ignorance or because they don't see a reason to bother, and so osMessageObject could be used to attack scripts either with the intent to compromise them or to screw them up.

Also, there is a difference that osMessageObject has with llRegionSayTo(), which is that it can be used to communicate with objects on another region.  Or at least I'm *assuming* it can communicate across regions.  It's been so long since I've discussed it, I might have some details wrong.

**Comment by mdickson** [comment]
Zauber good point on the data server event. Better to state that imo than simply say its poorly designed since any implementation would want to avoid that.   But that being said if you implement it but design it differently doesn't that screw up the portability issue you raised at the beginning?  IOW why implement it at all then if things like llRegionSayTo or http are also an option?

And no, osMessageObject afaik is region only.  It would be HUGELY expensive to do a grid wide "broadcast" mechanism for object to object communication. That's much better solved with http where the URL encodes the destination.

**Comment by zauberparacelsus** [comment]
Okay, if osMessageObject is region-local only, that resolves most of my concerns.  Reading the docs, the key in the dataserver event will be the UUID of the script that called osMessageObject?  That doesn't seem to make sense, do they mean the UUID of the object which contained that script?

**Comment by mdickson** [comment]
From reading code it looks like the key is the UUID of the prim the calling script is in not the script.  But a quick script to try it would be worth it.
DDoS is still an issue because there is no 'cost' for the call.

**Comment by zauberparacelsus** [comment]
Yeah.  There are other existing no-cost functions that can be used to DDoS stuff, so in theory it is no worse than existing stuff.

On that note, one thing I would still like to see implemented into Phlox would be some kind of "energy" system like in SL, or at least something to prevent misbehaving scripts from causing problems.

**Comment by kf6kjg** [comment]
I'm closing this with a wontfix. This isn't to say I wouldn't consider a patch someone wanted to submit that solved the problems presented and was well designed to fill a need, but because this issue as stated seems to have a consensus that it isn't needed.
