### ISSUE TITLE
Processing halcyon.ini changes.

### ISSUE THREAD

**Issue by sonjamichelle** [HalcyonGrid/halcyon#76]
When I make changes to halcyon.ini does the entire grid need to be restarted or just the user,grid and messaging servers?

**Comment by emperorstarfinder** [comment]
I find it better to restart everything i.e. UserServer, GridServer, MessageServer, InventoryServer, Regions to ensure that all services know about the changes in the Halcyon.ini file.  You probably could get away with just starting the services affected by that change but it is usually better to ensure all services have the current configurations information.

**Comment by kf6kjg** [comment]
As EmperorStarfinder commented it's safest to restart everything.

That said, if you changed something that only effected regions then you only **need** to reboot the relevant regions.  If you wanted to test an INI change on one region you can change that one region's INI and reboot it by itself.  There's lots of options here.

As to the grid services, IIRC they read a few things from the INI file, but mostly from their XML files so again it depends on what you change. As to the grid service XML files, I recommend only changing them while the service is offline as the services sometimes rewrite the files on shutdown. However if the user the grid service is running under doesn't have write permission to that file then you can edit freely: the service can't overwrite your changes at that point.
