### ISSUE TITLE
In-World Time did not change to PDT 

### ISSUE THREAD

**Issue by life777eternal** [HalcyonGrid/halcyon#79]
Hi, a friend of mine has Halcyon setup on [his own](https://gospellearningcenter.com/World.aspx) server and the time in-world did not change to PDT, it's still on PST.  Is there a way he can change that? (with a full grid restart maybe?) or is that a bug? 

Thank you.

**Comment by emperorstarfinder** [comment]
As far as I am aware there is no mechanism that automatically handles changing between PST and PDT in Halcyon.  Ideally, it is better for each grid to have their own time based upon the time that the server clock on the hardware where the grid server is on shows.  Unfortunately, the time for secondlife is hardcoded into the viewers through which should also be changed but that is something to take up with viewer devs.

**Comment by Vinhold** [comment]
World in question is my own world. This problem has not been repeated in other Halcyon world installations, so may be unique to how I have the world set up or the servers time configuration. I have not yet had time to update to Halcyon 0.9.41-master. So I do not consider this to be a real issue at this time.

**Comment by kf6kjg** [comment]
I think this is working as intended: not that it is correct for the time to fail to transition, but that the operating system and .Net are the main layers in control of time, not so much Halcyon itself.  If further investigation proves me wrong this can and should be reopened.
