### ISSUE TITLE
llLoopSound

### ISSUE THREAD

**Issue by sonjamichelle** [HalcyonGrid/halcyon#80]
Seems to be implemented in 
halcyon/InWorldz/InWorldz.Phlox.Engine/LSLSystemAPI.cs 

`        public void llLoopSound(string sound, float volume)
        {
            m_host.UpdateSound(KeyOrName(sound), volume, SoundFlags.Loop);
}`

So the following script SHOULD work:

```
//================
float volume = 1.0;
// This will determine how loud the sound will play (from 0 to 1)
integer on = TRUE;
// this is an integer (whole number) that switches between off (FALSE, or 0) and on (TRUE, or 1)
// We start with the integer set to TRUE (on)


default
{
    state_entry()
    {
            //If you want to script to do something whenever it starts, your code goes here
    }
 
    touch_start(integer x)
        // When touch starts
     
     {
        if (on == TRUE)
        {
             // Loop Sound
            llLoopSound("00a31197-3c8a-2d76-1ea0-09372a592ad7", 1);
             on = FALSE;
     
        }

    else if (on == FALSE)
        {
             // Stop Sound
             llStopSound();
             on = TRUE;
         
        }

    }
}

// ====================
```

But it doesn't. It only plays the sound once.

Am I missing something or is something broken?

**Comment by zauberparacelsus** [comment]
I had noticed cases in InWorldz where looped sounds would only play once.  However, this only occurred with objects which had been sitting in inventory unused for years, and a reset would fix them.

**Comment by sonjamichelle** [comment]
A reset didn't fix the issue.

**Comment by zauberparacelsus** [comment]
I didn't say it would, I was just referring to a secondary issue.

Does the problem still occur when llLoopSound is called on its own?

IE:
```
default {
    state_entry() {
        llLoopSound("00a31197-3c8a-2d76-1ea0-09372a592ad7", 1);
    }
}
```

**Comment by sonjamichelle** [comment]
Nope, works fine Kinda got a Star Trekking engine sound from that script.

**Comment by sonjamichelle** [comment]
Ok, everything seems to be working as expected. Not sure what was going on. Thanks for the help @zauberparacelsus 

Closing
