### ISSUE TITLE
Seaprate Servers (VMs) won't communicate with each other

### ISSUE THREAD

**Issue by sonjamichelle** [HalcyonGrid/halcyon#83]
Bear with me, I've been awake the past 36 hours chasing this problem.

I am running as of now the latest master as of 7am this morning. I have MySQL and Whip on Windows machine 1 along with 10 regions.

On Server 2 I have another 10 regions, Server 2,10 more, so on and so forth for 5 separate servers.

Anytime I cross a sim into another a region hosted on anything but the 1st main server I am missing objects, am a cloud and can't teleport to any other region.

Here is the console output and Halcyon.log

[console.txt](https://github.com/HalcyonGrid/halcyon/files/3150388/console.txt)

[Halcyon.log](https://github.com/HalcyonGrid/halcyon/files/3150389/Halcyon.log)

I see all kinds of error, but I have to be honest most of it is flying over my head right now.

I have tried with master branch, v.0.9.41 release and v0.9.40.6779 release. All exhibit the same problem.

It's got to be a misconfiged setting somewhere. I've checked firewall, redid it several times, checked halcyon.ini, region.ini, the xml configs. Everything LOOKS correct. There should be no reason why it's not working.

Networking and communication all work as expected on the OS level.

I'm ready to toss the whole thing and start from scratch at this point

**Comment by kf6kjg** [comment]
Looks like the region is having trouble communicating with a couple neighbors.

However I recommend asking support questions on the HalcyonGrid Discord support channel.  Issue reports should primarily be about the software not the operation thereof. :)

Also ping Vin if you haven't already: his growing list of problems and solutions is quite useful.  Maybe I'll convince him to put it on the wiki some time.

**Comment by Vinhold** [comment]
I am available to help. Post to me on Discord. Most likely a Windows network setup issue. I deal with it all the time in Grid operation.
