### ISSUE TITLE
Halcyon 0.9.41.41 Issues

### ISSUE THREAD

**Issue by Ana-Green** [HalcyonGrid/halcyon#84]
I write this for my Dad as he has problems to focus, he said he could not remember that the version was  0.9.41.41 but more like 0.9.41, [ CONSOLE  SHOW VERSION ] anyway issues are rez problems, Bob told they were related to Database Problems and had then manual to be fixed like add and clear tables.

Sounds a bit like "do it yourself" anyway Creator on some objects are unknown resulting that  Deed and add a group will not work, hence it's grey out. In some cases, I saw it myself was that Teleport board (Mesh) were just gone after a  relog they were back this all together is a problem.  [ See attachment ] Error retrieving inventory skeleton of agent xxxxxxx, extended HOME:<0,0> <0, 0> WAS <0,0> <0, 0, 0>! 

Thank  you, Daughter, from Frank  
Ana Green
  
![Grid User error](https://user-images.githubusercontent.com/36156774/57340029-62b86300-7134-11e9-8107-23cb2761ddb9.png)

**Comment by Ana-Green** [comment]
The same version, Database related I assume (does not clean table), says, Users online:1 but in fact nobody is online, needs to be fixed.  

Ana

**Comment by Ana-Green** [comment]
Messages, user  not  online  message  get  send then it  says:
[16:08:07] Grid Owner: Let me know when you are  back online
[16:08:07] Ms Dana: User is not logged in. Message not saved
[16:09:54] Grid Owner: Let me know when you are  back online
[16:09:54] Ms Dana: User is not logged in. Message not saved  

> **Repeating this  loop  and  it will say:**

[16:10:06] Grid Owner: Let me know when you are  back online
[16:10:07] Ms Dana: User is not logged in. Message saved.
[16:10:14] Grid Owner: Let me know when you are  back online
[16:10:14] Ms Dana: User is not logged in. Message saved.
[16:10:17] Grid Owner: Let me know when you are  back online
[16:10:17] Ms Dana: User is not logged in. Message saved.
[16:10:21] Grid Owner: Let me know when you are  back online
[16:10:21] Ms Dana: User is not logged in. Message saved.

Ana

**Comment by kf6kjg** [comment]
Please don't create combined issues: each individual issue should be reported individually so that each can have a clear discussion and understanding. If it is determined that two or more are actually caused or solved by the same thing, then good.

**Comment by Ana-Green** [comment]
Sure  n.p

**Comment by Vinhold** [comment]
Dreamcastle is currently running on Halcyon 0.9.41-master. This is the available precompiled copy posted on Github for Master as of 5/12/2019. The rez error has nothing to do with Halcyon, as it may be a corrupted item, and offline message problem has been reported in a subsequent issue report. The Rez error only happens on select items, not all the time on everything.

**Comment by kf6kjg** [comment]
I will close then in favor of the subsequent individualized issue reports.
