### ISSUE TITLE
Loading pictures in profiles

### ISSUE THREAD

**Issue by Ana-Green** [HalcyonGrid/halcyon#86]
Open Profile: the place where a picture should be is grey, same for other related picture showing it grey and says loading....

Regards,
Ana Green

**Comment by kf6kjg** [comment]
Which viewer?

**Comment by kf6kjg** [comment]
I saw you posted FS 5.0.11 in the other issue.

I just tested on 9.40 (Vin's GWGrid) and on latest master with a cache-cleared Firestorm 6.0.2 (56680) Feb  8 2019 23:11:19 (64bit) (Firestorm-Releasex64) with OpenSimulator support.  In both cases the texture showed up in the legacy profile view.

**Comment by Ana-Green** [comment]
In case that should step back to 9.40?  

It has been a long-standing problem and was not a high critical thing to fix. Dad is using Firestorm 5.0.11 (53634) Jan  9, 2018, 20:02:54 (Firestorm-Releasex64) with OpenSimulator support, because for him he said it works in general better.  

Extended: Bob said, It has not been solved at all yet. Only this one clue was the DB error field size was not large enough for what was being put into it. But making the field size larger only resolved the DB error, not the way the attachment is being processed or accessed. One of them has it wrong.

Regards,
Ana Green

**Comment by Vinhold** [comment]
Profile pictures are not a problem in Halcyon. I have already proven this with Frank. It is a problem with his viewer and we worked on clearing his cache to see if that was part of the issue. There may also be a FireStorm version problem as I do not think we are on the same viewer release. I am using FireStorm 6.0.2.56680. I have no problem placing a picture in my profile or seeing the Grid Owner profile picture in Dreamcastle world. I sent both screen captures of that to Frank on Skype. I also set my profile picture on my Gospel World account with no problem, it is running Halcyon 0.9.40.

**Comment by emperorstarfinder** [comment]
This is probably just a matter of updating the profile picture.  Usually, when a picture is grey it means the viewer is having trouble reaching that particular asset.  It may even be a default picture for the profile.  The quickest and easiest way to correct this would be to open your profile drag and drop your preferred picture on your profile's picture and click the okay button.  Assuming everything on the backend is working as it should (and I would say it is in this case) the picture should update and the grey picture should be fixed.

**Comment by kf6kjg** [comment]
In which case, I'm going to conclude that this is a local issue, not a Halcyon issue and close this report.  Thank you all.
